version: '2'

services:
  db:
    build: db/.
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: stalky
      MYSQL_USER: stalky
      MYSQL_PASSWORD: stalky
    volumes:
      - ./database:/var/lib/mysql

  www:
    build: ./server
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
      restart: always
      ports:
        - 8080:80
      volumes:
        - /sessions